apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-407900
  artifacts:
    - image: manuelextra/auth
    # - image: us.gcr.io/ticketing-dev-407900/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: manuelextra/client
    # - image: us.gcr.io/ticketing-dev-407900/auth
      context: client
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '**/*.js'
            dest: .
    - image: manuelextra/tickets
    # - image: us.gcr.io/ticketing-dev-407900/auth
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: .